version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.openjdk.jmh:jmh-generator-annprocess
    versions:
    - "1.29"
  - dependency-name: org.openjdk.jmh:jmh-core
    versions:
    - "1.29"
  - dependency-name: org.junit.vintage:junit-vintage-engine
    versions:
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter
    versions:
    - 5.7.1
